![alt text](https://whatsthebigdata.files.wordpress.com/2017/06/data-science-machine-learning-software-2015-2017.jpg)

##**NumPy**


NumPy(Numerica en Python)es una libreria de algebra lineal. Esta libreria es importante aprender porque:

1.   NumPy es muy es muy útil para realizar operaciones matemáticas y lógicas en una secuencia de datos de estructura numerica u otros tipos primitivos de tamaño fijo como bytes. Dicha secuencia se le llamara "array". 
2.   NumPy proporciona una gran cantidad de funciones útiles para operaciones en n-arrays  y matrices en Python. 

NumPy es una libreria importante en la que casi todos los paquetes de ciencia de datos o aprendizaje automático de Python dependen. Ejemplo: SciPy (Scientific Python), Mat-plotlib (libreria grafica), Scikit-learn, etc.



Documentación - https://numpy.org/doc/

###**Importar las librerias: Numpy y Pandas **

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print ("NumPy version - " + np.version.version)

NumPy version - 1.18.1


###**Crear un array, este es una secuencia de datos. Pudiendo ser numeros o letras**

####Creamos 1 D *array Numpy*

In [ ]:
#creamos 1D numpy array (secuencia de datos) desde una lista
array_1d = np.array([1, 2, 3, 4, 5])

print (array_1d)

[1 2 3 4 5]


In [ ]:
#creamos 1D numpy array desde una variable lista
list_1 = [11, 22, 33, 44, 55]
array_l1 = np.array(list_1)

print(array_l1)

[11 22 33 44 55]


In [ ]:
#Vemos que tipo de array numpy hemos creado
print ("Tipo de Array = " + str(type(array_1d)))

#Vemos que tipo de datos es 
print ("Tipo de dato = " + str(array_1d.dtype))

Tipo de Array = <class 'numpy.ndarray'>
Tipo de dato = int32


In [ ]:
#chequeamos que el tipo de matriz que hemos creado, sea solamente de 1 dimension
print(array_1d.shape)

(5,)


In [ ]:
type(array_1d)

numpy.ndarray

In [ ]:
#Demostración de la función rango (range)
plain_range = range(4,12)
list(plain_range)

[4, 5, 6, 7, 8, 9, 10, 11]

Observe cómo el segundo número es exclusivo.

In [ ]:
interval_range = range(1, 15, 2)

In [ ]:
list(interval_range)

[1, 3, 5, 7, 9, 11, 13]

### Tu turno de practicar!

1. Cree su propia lista de Python usando la función de range.
2. Convierta la lista en una NumPy array
3. Verifique el tipo de datos para asegurarse de que sea una NumPy array
4. Convierta esa array nuevamente en una lista




In [ ]:
list(range(15, 1, -2))

[15, 13, 11, 9, 7, 5, 3]

### Python Matrices (2D) a NumPy Array

In [ ]:
 mymatrix = [[4,2,9],[32,43,68],[73,8,9]]
 mymatrix
#mymatrix = [list(range(1,10,1)),list(range(2,12,1))]
#mymatrix

[[4, 2, 9], [32, 43, 68], [73, 8, 9]]

In [ ]:
#Creamos una matriz (2D array)
numpy_array = np.array(mymatrix)

In [ ]:
numpy_array

array([[ 4,  2,  9],
       [32, 43, 68],
       [73,  8,  9]])

In [ ]:
type(numpy_array)
numpy_array.dtype

dtype('int32')

### Transformar a NumPy Array en un Pandas DataFrame. DataFrame es una estructura de datos, la cual puede contener distintos tipos de elementos. 

In [ ]:
df_from_array = pd.DataFrame(numpy_array)
df_from_array

0   1   2
0   4   2   9
1  32  43  68
2  73   8   9

### Tu turno!

1. Crea tu propia matriz en Python
2. Convierte la matriz en NumPy array
3. Verifica el tipo de dato, para estar seguro que es NumPy array
4. Convierte NumPy array en un Pandas DataFrame

### Tipos de Datos en Python
1. int: Es un número entero
2. Float: Es un número real
3. str: Es una cadena de carácteres

In [ ]:
type(4)

int

In [ ]:
type(4.0)

float

In [ ]:
type('4353')

str

In [ ]:
type('Hello')

str

Función: DateTime

In [ ]:
import datetime
datetime_example = datetime.datetime.now()
print(datetime_example)

2021-03-30 17:38:30.270030


In [ ]:
type(datetime_example)

datetime.datetime

In [ ]:
another_list = [23, [34, 21], 'Google']
another_list

[23, [34, 21], 'Google']

###**Indexing, Slice indexing**
Indexing, significa Indexación. Nos referimos a ello cuando para indicar la posición de un elemento dentro del iterable. 
"Slice" significa obtener un subconjunto de elementos de un iterable en función de sus índices.

Ejemplo: Estoy por rendir un examen en el cual se le asignó un número a cada estudiante.Cuando llamanrón el número 11, entré porque sabia que era yo. Si hubieran llamado "Pasen del número 1 al 15", también hubiera entrado y este subconjunto es el "slice indexing". 

Recuerda que el index empieza en 0.


Se puede usar el slice indexing para extraer sub-regiones de ndarrays

Docuementación en: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

In [ ]:
#creamos 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7])
print (array_1d)

[1 2 3 4 5 6 7]


In [ ]:
#Como tenemos 1D array,solo se necesita realizar un index para acceder a cualquier posicion del elemento

#Si el valor del inde es 2
print ('Elementos en el index 2: ', array_1d[2])

#ndarrays son mutables,aqui cambiamos el elemento al indeex 2 
array_1d[2] = 10
print ('Elementos en el index 2 después del cambio: ', array_1d[2])

Elementos en el index 2:  3
Elementos en el index 2 después del cambio:  10


In [ ]:
print (array_1d)

[ 1  2 10  4  5  6  7]


In [ ]:
# Obtener los valores en el rango
print ('Elementos en el rango: ', array_1d[1:3]) #a:b - incluye a y excluye b

#Podemos cambiar los valores en el rango
array_1d[1:3] = 20
print ('Elementos en el rango despues del cambio: ', array_1d[1:3])

Elementos en el rango:  [ 2 10]
Elementos en el rango despues del cambio:  [20 20]


In [ ]:
#Para 2D arrays vamos a necesitar dos indexing, primero uno por la fila y el segundo por la columna
#Creamos 2D array
array_2d = np.array([[11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27], [31, 32, 33, 34, 35, 36, 37]])
print ('array original: \n', array_2d, '\n')

#slicing: Genera un array del mismo rango
array_copy = array_2d.copy()
slice_row = array_copy[1:2, :] #a:b - incluyendo a y excluyendo b
print ('sliced array on [1:2, :]: \n', slice_row)

array original: 
 [[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]] 

sliced array on [1:2, :]: 
 [[21 22 23 24 25 26 27]]


In [ ]:
# Si cambiamos el sliced array, se va a cambiar también el array original.
slice_row[:, :] = 10

print ('sliced array: \n', slice_row, '\n')
print ('original array: \n', array_2d)


sliced array: 
 [[10 10 10 10 10 10 10]] 

original array: 
 [[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]]


In [ ]:
#También se puede hacer el slicing por columnas
slice_col = array_2d[:, 1:5]
print (slice_col)

[[12 13 14 15]
 [22 23 24 25]
 [32 33 34 35]]


In [ ]:
# Podemos usar filtros para seleccinar los elementos que cumplen ciertos criterios.
#Seleccionamos los elementos que son mayores a 10
slice_col[slice_col>10]

array([12, 13, 14, 15, 22, 23, 24, 25, 32, 33, 34, 35])

In [ ]:
#Usando esta misma logica se pueden cambiar los elementos del array
#agregar 1 a todos los valores impares
slice_col[slice_col % 2 == 1] += 1
slice_col

array([[12, 14, 14, 16],
       [22, 24, 24, 26],
       [32, 34, 34, 36]])

###**Operaciones array aritmeticas**

Más información en: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

In [ ]:
#Las sumas pueden ser hechas con el signo de suma o con la función numpy: 'add' 
arr_x = np.array([[10, 20, 30], [40, 50, 60]])
arr_y = np.array([[11, 21, 31], [41, 51, 61]])

print("Array X")
print(arr_x, '\n')

print("Array Y")
print(arr_y, '\n')

print("Suma con los signos")
print (arr_x + arr_y, '\n')

print("Función suma de Numpy: add")
print (np.add(arr_x, arr_y))

Array X
[[10 20 30]
 [40 50 60]] 

Array Y
[[11 21 31]
 [41 51 61]] 

Suma con los signos
[[ 21  41  61]
 [ 81 101 121]] 

Función suma de Numpy: add
[[ 21  41  61]
 [ 81 101 121]]


In [ ]:
# Se realiza lo mismo con la resta 
print("Resta con los signos")
print (arr_y - arr_x, '\n')

print("Resta con la función Numpy: subtrac")
print (np.subtract(arr_y, arr_x))

Resta con los signos
[[1 1 1]
 [1 1 1]] 

Resta con la función Numpy: subtrac
[[1 1 1]
 [1 1 1]]


In [ ]:
# Multiplicación
print("Multiplicación con los signos")
print (arr_x * arr_y, '\n')

print("Multiplicación con la función Numpy: Multiply")
print (np.multiply(arr_x, arr_y))

Multiplicación con los signos
[[ 110  420  930]
 [1640 2550 3660]] 

Multiplicación con la función Numpy: Multiply
[[ 110  420  930]
 [1640 2550 3660]]


In [ ]:
#División
print("Division con los signos")
print (arr_y / arr_x, '\n')

print("División con la función Numpy: Divide")
print (np.divide(arr_y, arr_x))

Division con los signos
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]] 

División con la función Numpy: Divide
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]]


In [ ]:
#Raiz cuadrada

print (np.sqrt(arr_x))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [ ]:
#Exponente (e**x)

print (np.exp(arr_x))

[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [ ]:
#Potencia (x ** y)

print (np.power(arr_x, 3))

[[  1000   8000  27000]
 [ 64000 125000 216000]]


###**Metodos Estadisticos**

Más información en https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html


In [ ]:
#Crear una matriz aleatoria (random) de 4x6
arr = np.random.randn(4,6)
print (arr)

[[ 0.13942686  1.3266524  -2.52615814  0.25894765  1.33691189  0.62956501]
 [-0.48673843 -0.96741844 -0.69784397  0.86120658 -0.54381656 -0.51026398]
 [ 0.298096   -1.45606052  1.33802676 -1.95563428  1.83599864 -0.30172026]
 [-0.59327364  0.22871192  0.65417263 -1.47375346 -1.45903833 -0.26390252]]


In [ ]:
#Calcular la media (mean) de todos los elementos
print (arr.mean())

-0.18032942495016221


In [ ]:
# Media por fila
print (arr.mean(axis = 1))

[ 0.19422428 -0.39081247 -0.04021561 -0.4845139 ]


In [ ]:
#Media por columna
print (arr.mean(axis = 0))

[-0.1606223  -0.21702866 -0.30795068 -0.57730838  0.29251391 -0.11158044]


In [ ]:
#calcular la mediana para todos los elementos, por fila o columna. Se calcula de la misma manera que la media

print (np.median(arr))

-0.28281138808684136


*que significa eje (axis)?* https://stackoverflow.com/questions/22149584/what-does-axis-in-pandas-mean


In [ ]:
#Suma de todos los elementos, por fila o columna. Se calcula de la misma forma que se hizo con la media
print (np.sum(arr))

-4.327906198803893


In [ ]:
arr

array([[ 0.13942686,  1.3266524 , -2.52615814,  0.25894765,  1.33691189,
         0.62956501],
       [-0.48673843, -0.96741844, -0.69784397,  0.86120658, -0.54381656,
        -0.51026398],
       [ 0.298096  , -1.45606052,  1.33802676, -1.95563428,  1.83599864,
        -0.30172026],
       [-0.59327364,  0.22871192,  0.65417263, -1.47375346, -1.45903833,
        -0.26390252]])

###**Leer o escribir en disco**

In [ ]:
np.savetxt('array.txt', X = arr, delimiter = ',')

In [ ]:
np.loadtxt('array.txt', delimiter = ',')

array([[ 0.13942686,  1.3266524 , -2.52615814,  0.25894765,  1.33691189,
         0.62956501],
       [-0.48673843, -0.96741844, -0.69784397,  0.86120658, -0.54381656,
        -0.51026398],
       [ 0.298096  , -1.45606052,  1.33802676, -1.95563428,  1.83599864,
        -0.30172026],
       [-0.59327364,  0.22871192,  0.65417263, -1.47375346, -1.45903833,
        -0.26390252]])

##**Pandas**

Pandas es una libreria numérica de Python de código abierto que se construye sobre NumPy. 

Porqué es importante aprender Pandas:

Pandas permite realizar limpieza, preparación y análisis de datos. Además, funciona bien con datos de diferentes tipos de fuentes como: Hoja de Excel, archivo csv, archivo sql o incluso una página web

Documentación - https://pandas.pydata.org/pandas-docs/version/0.25.3/

###**Pandas Series**

La serie Pandas es una matriz etiquetada unidimensional que es capaz de contener datos de cualquier tipo

In [ ]:
#Creamos un panda series de una lista
ls = ['a', 'b', 'c', 'd', 'e']
ser_1 = pd.Series(ls)

print (ser_1)

0    a
1    b
2    c
3    d
4    e
dtype: object


In [ ]:
# Creamos una panda series desde un array
arr = np.array([10, 20, 30, 40, 50])
ser_2 = pd.Series(arr)

print (ser_2)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [ ]:
# Creamos una serie con una indexación especifica
ser_3 = pd.Series(arr, index = ['sarah', 'bob', 'alex', 'den', 'nancy'])

print (ser_3)

sarah    10
bob      20
alex     30
den      40
nancy    50
dtype: int32


In [ ]:
# Obtenemos un elemento mediante el index 
print (ser_3[3], '\n\n')
print (ser_3[[0, 2, 4]], '\n\n')
print (ser_3[:3])

40 


sarah    10
alex     30
nancy    50
dtype: int32 


sarah    10
bob      20
alex     30
dtype: int32


In [ ]:
#Obtenemos un elemento mediante la etiqueta del index 
print (ser_3['den'], '\n\n')
print (ser_3[['den', 'alex', 'sarah']])

40 


den      40
alex     30
sarah    10
dtype: int32


### Creamos un Pandas DataFrame

Pandas DataFrame es una estructura de datos bidimensional etiquetada.

In [ ]:
#Creamos a partir de una lista de listas
pet_info = [['Blain', 10, 'Dog'], ['Lucy', 4 , 'Cat'], ['Cinco', 8, 'Rabbit']]
pet_info

[['Blain', 10, 'Dog'], ['Lucy', 4, 'Cat'], ['Cinco', 8, 'Rabbit']]

In [ ]:
pet_df = pd.DataFrame(pet_info, columns = ['Name', 'Age', 'Type'],
                      index = ['A', 'B', 'C'])
                     
pet_df

Name  Age    Type
A  Blain   10     Dog
B   Lucy    4     Cat
C  Cinco    8  Rabbit

In [ ]:
pet_df['Name']

A    Blain
B     Lucy
C    Cinco
Name: Name, dtype: object

### Tú turno!

Observa el 'Tipo' de Columna

In [ ]:
type(pet_df)

pandas.core.frame.DataFrame

In [ ]:
pet_df.dtypes

Name    object
Age      int64
Type    object
dtype: object

### Tú turno!



In [ ]:
#Crea una lista de listas que contenga [[Month, Month #(Dec=12, etc.), Season]]
#Crea un Pandas DataFrame con las columnas = ['Month', 'Int', 'Season']

### iloc vs. loc

iloc - indexación basada en la posición (el índice siempre comienza con 0)

loc - indexación basada en etiquetas

Si no especifica índices, entonces iloc y loc serán iguales

In [ ]:
pet_df.iloc[0]

Name    Blain
Age        10
Type      Dog
Name: A, dtype: object

In [ ]:
pet_df.loc['B']

Name    Lucy
Age        4
Type     Cat
Name: B, dtype: object

### Aplicar conceptos a un Data Set (conjunto de datos)

In [ ]:
#Cargamos los datos de Iris desde Scikit-learn

from sklearn.datasets import load_iris 
iris = load_iris()
data = iris.data
column_names = iris.feature_names

In [ ]:
#columna
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
#fila
len(data)

150

### Slicing Arrays, listas, y Tuplas 
Slicing index siempre empieza en 0, lo que significa que el primer elemento es [0] y el segundo elemento es [1].

In [ ]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [ ]:
data[2:5]

array([[4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
data[0:10:2] #intervalos

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2]])

In [ ]:
#Convertir array en un Pandas DataFrame
df = pd.DataFrame(data, columns = column_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [ ]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [ ]:
df.loc[140:]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
df.mode()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.0               3.0                1.4               0.2
1                NaN               NaN                1.5               NaN

In [ ]:
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [ ]:
df['sepal length (cm)'].mean()

5.843333333333334

### Tú turno!

Encuentra la media de petal width

In [ ]:
df.groupby(['sepal width (cm)']).mean()

sepal length (cm)  petal length (cm)  petal width (cm)
sepal width (cm)                                                        
2.0                        5.000000           3.500000          1.000000
2.2                        6.066667           4.500000          1.333333
2.3                        5.325000           3.250000          0.975000
2.4                        5.300000           3.600000          1.033333
2.5                        5.762500           4.512500          1.550000
2.6                        6.160000           4.880000          1.420000
2.7                        5.855556           4.622222          1.555556
2.8                        6.335714           5.042857          1.707143
2.9                        6.060000           4.350000          1.320000
3.0                        6.015385           4.234615          1.403846
3.1                        6.036364           3.790909          1.245455
3.2                        5.884615           3.753846          1.261538
3.3                        6.016667           4.200000          1.566667
3.4                        5.316667           2.466667          0.716667
3.5                        5.150000           1.416667          0.300000
3.6                        5.425000           2.475000          0.750000
3.7                        5.266667           1.500000          0.266667
3.8                        6.100000           3.300000          0.900000
3.9                        5.400000           1.500000          0.400000
4.0                        5.800000           1.200000          0.200000
4.1                        5.200000           1.500000          0.100000
4.2                        5.500000           1.400000          0.200000
4.4                        5.700000           1.500000          0.400000

### Tú Turno! 

In [ ]:
from sklearn.datasets import load_boston
boston = load_boston()
data = boston.data
column_names = boston.feature_names

In [ ]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
df = pd.DataFrame(data, columns = column_names)
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]